In [8]:
import numpy as np
import pandas as pd 
import os

dataset = pd.read_csv("ratings_small.csv") 

dataset["ratingNew"]=np.where(dataset["rating"]<=2.5,0,1)
dataset=dataset[[
    "userId",
    "movieId",
    "ratingNew"
]].dropna(axis=0, how='any') 
 
X = dataset.iloc[:, 0:2].values  
y = dataset.iloc[:, 2].values 
print("Values of rating after conversion: ")
print(y)
X=dataset.drop('ratingNew',axis=1)
y=dataset['ratingNew']

Values of rating after conversion: 
[0 1 1 ... 1 0 1]


In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.33)

from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier()
classifier.fit(X_train,y_train)

predict_y=classifier.predict(X_test)

# precision, recall, f1-score, support
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(confusion_matrix(y_test,predict_y))
print(classification_report(y_test,predict_y))
print("Accuracy: ")
print(round(accuracy_score(y_test,predict_y)*100,2),'%')

[[ 1856  4040]
 [ 4115 22991]]
              precision    recall  f1-score   support

           0       0.31      0.31      0.31      5896
           1       0.85      0.85      0.85     27106

   micro avg       0.75      0.75      0.75     33002
   macro avg       0.58      0.58      0.58     33002
weighted avg       0.75      0.75      0.75     33002

Accuracy: 
75.29 %


In [14]:
print("Showing the predicted values for ratingNew: ")
print(predict_y)

Showing the predicted values for ratingNew: 
[0 1 1 ... 0 1 1]
